overblog_graphql:
    definitions:
        schema:
            default:
                query: Query
                mutation: Mutation
            # user:
            #     query: UserQuery
            #     mutation: UserMutation

            client:
                query: ClientQuery
                mutation: ClientMutation

            driver:
                query: DriverQuery
                mutation: DriverMutation

            admin:
                query: AdminQuery
                mutation: AdminMutation
        mappings:
            types:
                - # type: yaml
                  types: [yaml, graphql] # to include different types from the same dir
                  dir: "%kernel.project_dir%/config/graphql/types"
                  suffix: null

                - type: attribute
                  dir: "%kernel.project_dir%/src/Entity"
                  suffix: null

                - type: attribute
                  dir: "%kernel.project_dir%/src/GraphQL"
                  suffix: null

                - type: attribute
                  dir: "%kernel.project_dir%/src/CQRS"
                  suffix: null
