# VehicleStatus:
#     type: enum
#     config:
#         enumClass: App\Entity\Transport\Vehicle\VehicleStatus
#         # values:
#         #     GREEN:
#         #         description: "The color green"

UploadFile:
  type: custom-scalar
  config:
    scalarType: '@=newObject("Overblog\\GraphQLBundle\\Upload\\Type\\GraphQLUploadType")'

FileURI:
    type: custom-scalar
    config:
        scalarType: '@=service("App\\GraphQL\\Type\\Scalar\\FileType")'